import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import crypto from 'node:crypto';
import {validateCoordinateSupplement} from '../src/mapCoordinateSupplement.js';
const source=fs.readFileSync(new URL('../integrations/hub/HubProductionCoordinates.js',import.meta.url),'utf8')+'\n'+fs.readFileSync(new URL('../integrations/hub/HubProductionCoordinateStore.js',import.meta.url),'utf8');
const c=vm.createContext({hubStageModelHash_:v=>crypto.createHash('sha256').update(JSON.stringify(v),'utf8').digest('hex')});vm.runInContext(source,c);
test('Hub coordinate manifest verifies with Node UTF8 contract',()=>{const v=c.hubProductionCoordinateEnvelope_([{customerCode:'S12345',group:'honam',lat:35,lng:127,address:'전남 순천시 중앙로 1',source:'STORED_MATCH',checkedAt:'2026-09-29T00:00:00Z'}],'2026-09-29T00:00:00Z');assert.equal(validateCoordinateSupplement(v).body.rows.length,1);});
test('Kakao requires exact normalized address and unique candidate',()=>{const address='부산광역시 중구 중앙대로 1',d={address_name:address,x:'129.07',y:'35.17'};assert.equal(c.hubProductionCoordinateKakaoChoice_({documents:[d],meta:{is_end:true}},address).status,'KAKAO_EXACT_ADDRESS');assert.equal(c.hubProductionCoordinateKakaoChoice_({documents:[d,d]},address).status,'KAKAO_AMBIGUOUS');assert.equal(c.hubProductionCoordinateKakaoChoice_({documents:[d]},'부산 중구 중앙대로 2').status,'KAKAO_ADDRESS_MISMATCH');});
test('Kakao incomplete pages and invalid coordinates cannot publish',()=>{assert.equal(c.hubProductionCoordinateKakaoChoice_({documents:[],meta:{is_end:false}},'부산 중구 중앙대로 1').status,'KAKAO_INCOMPLETE');assert.equal(c.hubProductionCoordinateKakaoChoice_({documents:[{address_name:'부산 중구 중앙대로 1',x:0,y:0}]},'부산 중구 중앙대로 1').status,'KAKAO_COORDINATE_INVALID');});
test('permission failure stops geocoding without printing source response',()=>{let calls=0;c.UrlFetchApp={fetch:()=>{calls++;return {getResponseCode:()=>403,getContentText:()=>{throw Error('must not read');}};}};assert.throws(()=>c.hubProductionCoordinateGeocode_('부산 중구 중앙대로 1','synthetic'),/MODEL_COORD_KAKAO_HTTP_403/);assert.equal(calls,1);});
test('coordinate store never mutates Customer, Archive, shards or published pointer',()=>{assert(!/setValues|deleteRows|setContent|hubStageModelSave_|newTrigger/.test(source));assert(!/setProperty\(HUB_STAGE_MODEL/.test(source));});
