import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../integrations/hub/HubMapAutomation.js',import.meta.url),'utf8');
function fixture(){
 const props=new Map();let triggers=['customerWatchdog','hubStageReadModelRestoreContinue'],requests=0,restore={phase:'DONE'},job=null,result={phase:'UP_TO_DATE',generation:9};
 const ctx=vm.createContext({Date,JSON,console:{log(){}},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props.get(k)||null,setProperty(k,v){assert.equal(k,'PHASE2B_PRODUCTION_MAP_AUTOMATION_V1');props.set(k,v);}})},LockService:{getUserLock:()=>({tryLock:()=>true,releaseLock(){}})},
  ScriptApp:{getProjectTriggers:()=>triggers.map(x=>({getHandlerFunction:()=>x})),newTrigger(name){assert.equal(name,'hubProductionMapAutoTick');return{timeBased(){return this;},everyHours(n){assert.equal(n,1);return this;},create(){triggers.push(name);}};}},
  hubStageRestoreLoad_:()=>restore,hubMapIncrementalLoad_:()=>job,hubStageModelLoad_:()=>({stateId:'new',commitHttp:200,verifiedFingerprint:'fp'}),hubStageRestoreManifest_:()=>({fingerprint:'fp'}),hubMapIncrementalRequest_:()=>{requests++;return{data:result};}});
 vm.runInContext(source,ctx);
 return{ctx,props,get requests(){return requests;},get triggers(){return triggers;},set restore(v){restore=v;},set job(v){job=v;},set result(v){result=v;},get status(){return ctx.hubMapAutomationStatus_();}};
}
test('automatic registration is idempotent and requires actual manual publish proof',()=>{const f=fixture();assert.throws(()=>f.ctx.hubProductionMapAutoInstall(),/MANUAL_PASS_REQUIRED/);f.job={stateId:'new',phase:'DONE',publication:'PUBLISHED'};f.ctx.hubProductionMapAutoInstall();f.ctx.hubProductionMapAutoInstall();assert.deepEqual(f.triggers,['customerWatchdog','hubStageReadModelRestoreContinue','hubProductionMapAutoTick']);assert.equal(f.status.status,'REGISTERED_NOT_RUN');assert.equal(f.status.lastSuccess,null);});
test('restore, candidate and error states do not start another map job',()=>{for(const state of ['RESTORE','ERROR']){const f=fixture();f.restore={phase:state};f.ctx.hubProductionMapAutoTick();assert.equal(f.requests,0);}for(const state of ['BUILD','SEND','ERROR']){const f=fixture();f.job={phase:state,generation:8};f.ctx.hubProductionMapAutoTick();assert.equal(f.requests,0);}});
test('unchanged stored dates are NOOP, not a new successful publication',()=>{const f=fixture();f.ctx.hubProductionMapAutoTick();assert.equal(f.requests,1);assert.equal(JSON.parse([...f.props.values()][0]).status,'NOOP');assert.equal(f.status.lastSuccess,null);});
test('request evidence and completed publication evidence stay distinct',()=>{const f=fixture();f.result={phase:'BUILD',generation:10};f.ctx.hubProductionMapAutoTick();assert.equal(f.status.lastSuccess,null);f.job={origin:'AUTO',phase:'DONE',publication:'PUBLISHED',stateId:'new',commitHttp:200,updatedAt:'2026-09-29T03:00:00Z',generation:10};f.result={phase:'UP_TO_DATE'};f.ctx.hubProductionMapAutoTick();assert.equal(f.status.lastSuccess,'2026-09-29T03:00:00Z');});
test('manual publication is not recorded as automatic success',()=>{const f=fixture();f.job={origin:'MANUAL',phase:'DONE',publication:'PUBLISHED',stateId:'new',commitHttp:200,updatedAt:'2026-09-29T03:00:00Z',generation:10};f.ctx.hubProductionMapAutoTick();assert.equal(f.status.lastSuccess,null);});
test('unsafe exception text is never recorded in automation state',()=>{const f=fixture();f.ctx.hubMapIncrementalRequest_=()=>{throw Error('token=SYNTHETIC_PRIVATE');};f.ctx.hubProductionMapAutoTick();assert.equal(f.status.lastError,'MODEL_AUTOMATION_FAILED');assert(!JSON.stringify([...f.props.values()]).includes('SYNTHETIC'));});
test('no source mutation, Stage trigger deletion or source recollection in map automation',()=>{assert(!/deleteTrigger|setValues|deleteRows|collector\/|runFullSync/.test(source));});
