import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {checkPeriodPage,groupPeriodRows,validatePeriod,createPeriodJobs,readStaffDriverHistory,selectPeriodStores} from '../src/mapPeriod.js';
import '../public/map-period-ui.js';
const row=(n,patch={})=>({customerCode:'S1234',sourceKey:'K'+n,deliveryDate:'2026-08-01',lastDeliveryDate:'2026-08-01',vehicle:'101',driverName:'TEST A',driverKey:'A',...patch});
const job=()=>({startDate:'2026-07-17',endDate:'2026-09-14',count:0,total:null,keys:new Set(),cursors:new Set()});
const page=(data,{offset=0,scan=0,read=data.length,total=read,more=false,cursor='NEXT',matched=offset+data.length}={})=>({ok:true,data,meta:{contract:'period-assignments-v2',startDate:'2026-07-17',endDate:'2026-09-14',count:data.length,pageSize:1000,pageOffset:offset,sourceOffset:scan,sourceReadCount:read,sourceTotal:total,scannedCount:scan+read,totalCount:more?null:matched,sourceCount:more?null:matched,hasMore:more,complete:!more,nextCursor:more?cursor:null,truncated:false}});
for(const days of [1,7,60,90])test(`period ${days}-day date contract`,()=>{const end='2026-09-14',start=new Date(Date.parse(end)-(days-1)*86400000).toISOString().slice(0,10);assert.deepEqual(validatePeriod(start,end),{startDate:start,endDate:end});});
for(const size of [0,23,1000])test(`period complete ${size} rows`,()=>{const j=job();checkPeriodPage(page(Array.from({length:size},(_,i)=>row(i))),j);assert.equal(j.count,size);});
test('period >1000 pages remain incomplete until all source rows consumed',()=>{const j=job();checkPeriodPage(page(Array.from({length:1000},(_,i)=>row(i)),{total:1007,more:true}),j);assert.equal(j.total,null);checkPeriodPage(page(Array.from({length:7},(_,i)=>row(i+1000)),{offset:1000,scan:1000,total:1007}),j);assert.equal(j.total,1007);});
test('legacy date envelope includes outside dates: source progress differs from returned count',()=>{const j=job();checkPeriodPage(page([row(1)],{read:43,total:44,more:true}),j);checkPeriodPage(page([row(2)],{offset:1,scan:43,total:44}),j);assert.equal(j.count,2);assert.equal(j.scannedCount,44);});
test('empty filtered intermediate page advances only the source cursor',()=>{const j=job();checkPeriodPage(page([],{read:1000,total:1001,more:true}),j);checkPeriodPage(page([row(1)],{scan:1000,total:1001}),j);assert.equal(j.count,1);});
test('source totals changing, stalled cursor, false complete all fail closed',()=>{for(const patch of [{sourceTotal:2},{scannedCount:0},{complete:false},{truncated:true},{totalCount:null}]){const p=page([row(1)]);Object.assign(p.meta,patch);assert.throws(()=>checkPeriodPage(p,job()),/INCOMPLETE/);}});
test('middle page failure hides partial rows and retry preserves checkpoint',async()=>{let fail=true,n=0;const scheduled=[];const jobs=createPeriodJobs({schedule:f=>(scheduled.push(f),{unref(){}}),loadPage:async()=>{if(n++===0)return page([row(1)],{total:2,more:true});if(fail)throw new Error('FAIL');return page([row(2)],{offset:1,scan:1,total:2});}});jobs.read('2026-07-17','2026-09-14');for(let i=0;i<4;i++){scheduled.shift()();await new Promise(setImmediate);}assert.equal(jobs.read('2026-07-17','2026-09-14').data,null);fail=false;jobs.read('2026-07-17','2026-09-14',{retry:true});scheduled.shift()();await new Promise(setImmediate);assert.equal(jobs.read('2026-07-17','2026-09-14').meta.complete,true);});
test('duplicate rows dedupe without losing multi-date or multi-vehicle history',()=>{const rows=groupPeriodRows([row(1),row(1),row(2,{vehicle:'202'}),row(3,{deliveryDate:'2026-08-02',lastDeliveryDate:'2026-08-02'})]);assert.equal(rows[0].history.length,3);});
test('vehicle filter uses matching latest history, not overall representative',()=>{const rows=groupPeriodRows([row(1),row(2,{vehicle:'202',deliveryDate:'2026-08-02',lastDeliveryDate:'2026-08-02'})]);assert.equal(MapPeriodUi.select(rows,['101'])[0].vehicle,'101');assert.equal(rows[0].vehicle,'202');});
test('one historical driver across multiple vehicles stays one identity',()=>{const rows=groupPeriodRows([row(1),row(2,{vehicle:'202',deliveryDate:'2026-08-02',lastDeliveryDate:'2026-08-02'})]);const selected=MapPeriodUi.select(rows,[],'A');assert.equal(selected.length,1);assert.equal(selected[0].history.length,2);});
test('latest representative never overwritten by an older row',()=>{const rows=groupPeriodRows([row(2,{vehicle:'202',deliveryDate:'2026-08-02',lastDeliveryDate:'2026-08-02'}),row(1)]);assert.equal(rows[0].vehicle,'202');});
const historySource=fs.readFileSync(new URL('../integrations/hub/HubStaffHistory.js',import.meta.url),'utf8');
function historyFixture({phone='SYNTHETIC_CONTACT',http=200,invalidJson=false}={}){
 const headers=['deliveryDate','confirmedVehicle','baseVehicle','truckTon','driverName','driverPhone','deliveryArea','customerCode','customerName','salesAmount','deliveryCount','customerAddress','detailAddress','accessMemo','createdAt','updatedAt','hashKey'];
 const rows=[['2026. 8. 1','101','','','HISTORICAL',phone,'','S1234'],['8/2/2026','202','','','HISTORICAL',phone,'','S1234']];
 const saved=new Map();let requests=0,lookups=0;const calls=[];
 const sheet={getLastRow:()=>3,getLastColumn:()=>headers.length,getSheetId:()=>9,getRange:(r,c,n)=>r===1?{getValues:()=>[headers]}:{createTextFinder:code=>({matchEntireCell(){return this;},useRegularExpression(){return this;},findAll(){lookups++;return[{getRow:()=>2},{getRow:()=>3}];}})}};
 const context=vm.createContext({Date,Number,String,Array,Set,JSON,Error,HUB_DEFAULT_SOURCE_ID:'CURRENT',HUB_STAFF_DETAIL_ARCHIVE:'ARCHIVE',CustomerDataApi:{getDailyRoutes:()=>({ok:true,meta:{source:'Current'}})},
  SpreadsheetApp:{openById:id=>{assert.equal(id,'CURRENT');return{getSheetByName:()=>sheet};}},CacheService:{getScriptCache:()=>({get:k=>saved.get(k),put:(k,v)=>saved.set(k,v),remove:k=>saved.delete(k)})},
  hubDataCacheKey_:(name,p)=>name+JSON.stringify(p),hubStaffDetailDate_:x=>String(x),ScriptApp:{getOAuthToken:()=> 'SYNTHETIC_TOKEN'},
  UrlFetchApp:{fetch:(url,options)=>{requests++;const body=JSON.parse(options.payload);calls.push(body);return{getResponseCode:()=>http,getContentText:()=>invalidJson?'not-json':JSON.stringify({valueRanges:body.dataFilters.map(f=>({dataFilters:[{gridRange:{...f.gridRange}}],valueRange:{values:[rows[f.gridRange.startRowIndex-1].slice(f.gridRange.startColumnIndex,f.gridRange.endColumnIndex)]}})).reverse()})};}}});
 vm.runInContext(historySource,context);return{context,saved,calls,requests:()=>requests,lookups:()=>lookups};
}
test('protected history reads existing historical contact, not current master',()=>{const f=historyFixture(),h=f.context.hubStaffHistorySource_('S1234','2026-08-01','2026-08-02');assert.equal(h.rows.length,2);assert.equal(h.rows[0].driverName,'HISTORICAL');assert.equal(h.rows[0].driverPhone,'SYNTHETIC_CONTACT');assert.equal(h.rows[0].deliveryDate,'2026-08-02');});
test('history missing phone stays empty, never substitutes owner phone',()=>{const f=historyFixture({phone:''}),h=f.context.hubStaffHistorySource_('S1234','2026-08-01','2026-08-02');assert.equal(h.rows[0].driverPhone,'');assert.equal('accessMemo' in h.rows[0],false);});
test('history batches sparse rows and caches only locators, rereading contact each time',()=>{const f=historyFixture();for(let i=0;i<2;i++)f.context.hubStaffHistorySource_('S1234','2026-08-01','2026-08-02');assert.equal(f.requests(),2);assert.equal(f.lookups(),1);assert.ok([...f.saved.values()].every(v=>!v.includes('SYNTHETIC')&&!v.includes('HISTORICAL')));assert.ok(f.calls.flatMap(b=>b.dataFilters).every(f=>f.gridRange.endRowIndex-f.gridRange.startRowIndex===1));});
test('history range filter excludes older visits without dropping matching visits',()=>{const f=historyFixture(),h=f.context.hubStaffHistorySource_('S1234','2026-08-02','2026-08-02');assert.equal(h.rows.length,1);});
test('history Sheets 5xx mapping is sanitized',()=>assert.throws(()=>historyFixture({http:503}).context.hubStaffHistorySource_('S1234','2026-08-01','2026-08-02'),/HISTORY_SHEETS_HTTP_503/));
test('history invalid JSON is explicit and never returns partial success',()=>assert.throws(()=>historyFixture({invalidJson:true}).context.hubStaffHistorySource_('S1234','2026-08-01','2026-08-02'),/HISTORY_SHEETS_INVALID_JSON/));
test('history transport timeout propagates without partial success',async()=>{await assert.rejects(readStaffDriverHistory({customerCode:'S1234',startDate:'2026-08-01',endDate:'2026-08-02'},async()=>{throw Object.assign(new Error('TIMEOUT'),{name:'AbortError'});}),{name:'AbortError'});});
test('date formats include Sheets dates, reject invalid calendar dates',()=>{const f=historyFixture();assert.equal(f.context.hubStaffHistoryDate_('2026. 8. 1'),'2026-08-01');assert.equal(f.context.hubStaffHistoryDate_('8/2/2026'),'2026-08-02');assert.equal(f.context.hubStaffHistoryDate_('2026-02-30'),null);assert.equal(f.context.hubStaffHistoryDate_('delivery_admin'),null);});
test('server-side vehicle/driver projections preserve every dated history and enforce exclusivity',()=>{const rows=groupPeriodRows([row(1),row(2,{vehicle:'202',deliveryDate:'2026-08-02',lastDeliveryDate:'2026-08-02'})]);const selected=selectPeriodStores(rows,{vehicle:'101'});assert.equal(selected[0].vehicle,'101');assert.equal(selected[0].history.length,2);assert.equal(selectPeriodStores(rows,{driverKey:'A'}).length,1);assert.throws(()=>selectPeriodStores(rows,{vehicle:'101',driverKey:'A'}));});
test('bounded period reads only allowlisted columns within the established physical envelope',()=>{
 const headers=['deliveryDate','confirmedVehicle','baseVehicle','truckTon','driverName','driverPhone','deliveryArea','customerCode','customerName','salesAmount','deliveryCount','customerAddress','detailAddress','accessMemo','createdAt','updatedAt','hashKey'];
 const values=[['2026. 8. 1','101','','','TEST','SYNTHETIC_CONTACT','','S1234','TEST','','','TEST ADDRESS','','FORBIDDEN','','','K1'],['2026. 8. 2','202','','','TEST','SYNTHETIC_CONTACT','','S1234','TEST','','','TEST ADDRESS','','FORBIDDEN','','','K2']];let calls=0;
 const context=vm.createContext({Date,Number,String,Array,Set,JSON,Error,HUB_DEFAULT_SOURCE_ID:'CURRENT',
  SpreadsheetApp:{openById:()=>({getSheetByName:()=>({getLastRow:()=>3,getSheetId:()=>9,getLastColumn:()=>headers.length,getRange:()=>({getValues:()=>[headers]})})})},
  ScriptApp:{getOAuthToken:()=> 'SYNTHETIC'},hubMapHttpRaise_:code=>{throw new Error(code);},hubStaffHistoryDate_:value=>String(value).replace(/\. /g,'-').replace(/-(\d)(?=-|$)/g,'-0$1'),
  UrlFetchApp:{fetch:(url,options)=>{calls++;const body=JSON.parse(options.payload);assert.ok(body.dataFilters.every(f=>f.gridRange.endRowIndex-f.gridRange.startRowIndex<=1000));assert.ok(body.dataFilters.every(f=>!(f.gridRange.startColumnIndex<=13&&f.gridRange.endColumnIndex>13)));return{getResponseCode:()=>200,getContentText:()=>JSON.stringify({valueRanges:body.dataFilters.map(f=>({dataFilters:[f],valueRange:{values:values.map(r=>r.slice(f.gridRange.startColumnIndex,f.gridRange.endColumnIndex))}}))})};}}});
 vm.runInContext(fs.readFileSync(new URL('../integrations/hub/HubPeriodSource.js',import.meta.url),'utf8'),context);
 const result=context.hubPeriodReadBounded_({first:2,total:2,last:3,sheetId:9},0,1000);assert.equal(result.data.length,2);assert.equal(result.data[1].customerCode,'S1234');assert.equal('accessMemo'in result.data[1],false);assert.equal(result.meta.nextToken,null);assert.equal(calls,1);
 assert.throws(()=>context.hubPeriodReadBounded_({first:2,total:2,last:4,sheetId:9},0,1000),/PERIOD_SOURCE_INCOMPLETE/);
});
