import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import vm from 'node:vm';
import {createStageReadModel} from '../src/stageReadModel.js';
import '../public/phase2b-ui-helpers.js';
const secret='synthetic-test-only-secret-0000000000';
const digest=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
const h=(id='task1',patch={})=>({deliveryDate:'2026-09-01',customerCode:'S1001',deliveryId:id,vehicle:'용38',driverName:'SYNTHETIC',driverPhone:'SYNTHETIC',kind:'ASSIGNED',sourceVersion:'v1',updatedAt:'2026-09-02',...patch});
const p=(patch={})=>({deliveryDate:'2026-09-01',customerCode:'S1001',vehicle:'101',driverName:'SYNTHETIC',driverKey:'key1',driverIdentity:'NAME_CONTACT',...patch});
function fixture(){const model=createStageReadModel({secret});const send=message=>{const body={timestamp:String(Date.now()),nonce:crypto.randomBytes(18).toString('hex'),message};model.ingest(body,crypto.createHmac('sha256',secret).update(JSON.stringify(body)).digest('hex'));};return{model,send};}
function publish(f,gen=1,hr=[h()],pr=[p()]){f.send({type:'begin',generation:gen});const manifest=[];for(const[k,rows]of [['history',hr],['period',pr]]){f.send({type:'shard',generation:gen,kind:k,date:'2026-09-01',rows,hash:digest(rows)});manifest.push({key:k+':2026-09-01',hash:digest(rows),count:rows.length});}f.send({type:'commit',generation:gen,startDate:'2026-08-01',endDate:'2026-09-15',manifest});}
test('protected lookup is exact, sorted, minimal, and independent of Google',()=>{const f=fixture();publish(f,1,[h(),h('task2',{vehicle:'202'})]);const rows=f.model.history({customerCode:'S1001',startDate:'2026-09-01',endDate:'2026-09-15'});assert.equal(rows.length,2);assert.equal(rows[1].vehicle,'202');assert.equal(rows[0].driverPhone,'SYNTHETIC');assert.equal('sourceVersion'in rows[0],false);assert.equal(f.model.history({customerCode:'S1002',startDate:'2026-09-01',endDate:'2026-09-15'}).length,0);});
test('no model means no raw fallback, and partial generation is never published',()=>{const f=fixture();assert.throws(()=>f.model.period('2026-09-01','2026-09-15'),/NOT_READY/);f.send({type:'begin',generation:1});assert.equal(f.model.status().ready,false);assert.throws(()=>f.send({type:'commit',generation:1,startDate:'2026-08-01',endDate:'2026-09-15',manifest:[{key:'history:2026-09-01',hash:'x',count:1}]}),/INCOMPLETE/);});
test('idempotent shard resend and lost commit ACK preserve published generation',()=>{const f=fixture();publish(f);publish(f);assert.equal(f.model.status().historyRows,1);f.send({type:'begin',generation:2});assert.equal(f.model.status().ready,true);assert.equal(f.model.history({customerCode:'S1001',startDate:'2026-09-01',endDate:'2026-09-15'}).length,1);});
test('reject anonymous/tampered payload and secret-bearing raw fields',()=>{const f=fixture();assert.throws(()=>f.model.ingest({},''),/AUTH/);f.send({type:'begin',generation:1});for(const key of ['rawPayload','location','accessInfo','ownerPhone','memo']){const rows=[h('task1',{[key]:'synthetic'})];assert.throws(()=>f.send({type:'shard',generation:1,kind:'history',date:'2026-09-01',rows,hash:digest(rows)}),/MODEL_ROW/);}});
test('public period contains no phone and preserves vehicle/driver relations',()=>{const f=fixture();publish(f,1,[h()],[p(),p({vehicle:'202',driverKey:'key2'})]);const r=f.model.period('2026-09-01','2026-09-15');assert.equal(r.data[0].history.length,2);assert.equal(r.data[0].lastDeliveryDate,'2026-09-01');assert.equal(JSON.stringify(r).includes('driverPhone'),false);assert.throws(()=>f.model.period('2026-07-01','2026-09-15'),/RANGE_NOT_READY/);});
test('duplicate task in a shard and hash mismatch fail closed',()=>{const f=fixture();f.send({type:'begin',generation:1});for(const[rows,hash]of [[[h(),h()],digest([h(),h()])],[[h()],'wrong']])assert.throws(()=>f.send({type:'shard',generation:1,kind:'history',date:'2026-09-01',rows,hash}),/MODEL_/);});
test('vehicle display normalization never mutates keys or doubles suffix',()=>{for(const[a,b]of [['용38','용38호'],['용 20 호','용20호'],['101','101호'],['101호호','101호'],['101\n호','101호'],['','']])assert.equal(Phase2bUi.normalizeVehicleLabel(a),b);});
test('durable builder is isolated and avoids full RAW copying and Customer writes',()=>{const code=fs.readFileSync(new URL('../integrations/hub/HubStageReadModel.js',import.meta.url),'utf8');new vm.Script(code);assert.match(code,/batch:1000/);assert.match(code,/PHASE2B_STAGE_READ_MODEL_V1/);assert.match(code,/hubStageModelSave_\(s\)/);assert.match(code,/hubStageModelSchedule_\(\)/);assert.doesNotMatch(code,/\.deleteRows\(|\.setValues\(|runFullSync|DAILYMON|getDataRange\(/);assert.match(code,/freshon-admin-stage-preview-template\.onrender\.com/);});
test('maintenance runs multiple chunks, persists each and preserves state across execution objects',()=>{
 const source=fs.readFileSync(new URL('../integrations/hub/HubStageReadModel.js',import.meta.url),'utf8');
 let stored={phase:'BUILD',source:0,sources:[{},{},{}],shards:{},generation:1,scanned:0},writes=0,batches=0,triggers=[],released=0;
 const ctx=vm.createContext({console:{warn(){}},Date,LockService:{getUserLock:()=>({tryLock:()=>true,releaseLock:()=>released++})},ScriptApp:{getProjectTriggers:()=>triggers,deleteTrigger:t=>{triggers=triggers.filter(x=>x!==t);},newTrigger:name=>({timeBased(){return this;},after(){return this;},create(){triggers.push({getHandlerFunction:()=>name});}})}});
 vm.runInContext(source,ctx);ctx.hubStageModelLoad_=()=>JSON.parse(JSON.stringify(stored));ctx.hubStageModelSave_=s=>{writes++;stored=JSON.parse(JSON.stringify(s));};ctx.hubStageModelBuildBatch_=s=>{batches++;s.scanned+=1000;s.source++;};ctx.hubStageModelSend_=()=>{};
 ctx.hubStageReadModelContinue();assert.equal(batches,3);assert.equal(stored.phase,'DONE');assert.ok(writes>=5);assert.equal(triggers.length,0);assert.equal(released,1);
 stored={...stored,phase:'BUILD',source:0};ctx.hubStageModelBuildBatch_=()=>{throw Error('MODEL_SOURCE_HTTP_503');};
 for(let i=0;i<3;i++)ctx.hubStageReadModelContinue();assert.equal(stored.phase,'ERROR');assert.equal(stored.errors,3);assert.equal(triggers.length,0);assert.equal(stored.scanned,3000);
});
